#service:
#     port: 8080

management:
  security:
   enabled: false  #关掉安全认证
  port: 8888     #管理端口调整成8888
  context-path: /123  #actuator的访问路径
  
  
#配置端点
  endpoints:
    actuator:
       enabled: true
    shutdown: 
       enabled: true


    